/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package OOM_PROJECT;

/**
 *
 * @author Taru
 */
public class AccountDetails extends javax.swing.JDialog {

    /**
     * Creates new form AccountDetails
     */
    public AccountDetails(java.awt.Frame parent, boolean modal,Customer customer) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(parent);
        first.setText(customer.getFirstName());
        last.setText(customer.getLastName());
        mobile.setText(customer.getMobile());
        accountno.setText(customer.getAccount().getAccountno());
        accounttype.setText(customer.getAccount().getAccounttype());
        balance.setText(String.format("%.2f",customer.getAccount().BalanceEnquiry()));
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        First = new javax.swing.JLabel();
        first = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        last = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        mobile = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        accountno = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        accounttype = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        balance = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Account Details");
        getContentPane().setLayout(new java.awt.GridLayout(7, 2, 5, 5));

        First.setText("First Name");
        getContentPane().add(First);
        getContentPane().add(first);

        jLabel2.setText("Last Name");
        getContentPane().add(jLabel2);
        getContentPane().add(last);

        jLabel4.setText("Mobile No");
        getContentPane().add(jLabel4);
        getContentPane().add(mobile);

        jLabel9.setText("Account No:");
        getContentPane().add(jLabel9);
        getContentPane().add(accountno);

        jLabel6.setText("Acount Type:");
        getContentPane().add(jLabel6);
        getContentPane().add(accounttype);

        jLabel7.setText("Balance ");
        getContentPane().add(jLabel7);
        getContentPane().add(balance);

        jButton1.setText("OK");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel First;
    private javax.swing.JLabel accountno;
    private javax.swing.JLabel accounttype;
    private javax.swing.JLabel balance;
    private javax.swing.JLabel first;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel last;
    private javax.swing.JLabel mobile;
    // End of variables declaration//GEN-END:variables
}
